import { Inter } from 'next/font/google'
import './globals.css'
import 'animate.css';
import "react-responsive-carousel/lib/styles/carousel.min.css"
import Navbar from '@/components/common/Navbar'
import Footer from '@/components/common/Footer';
import BackToTop from '@/components/common/BackToTop';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: `Truva Turkish Kitchen`,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{padding:0}}>
        <Navbar />
        {children}
          <BackToTop />
        <Footer />
      </body>
    </html>
  )
}
